-- AlterTable
ALTER TABLE `menu` ADD COLUMN `contactImagePath` VARCHAR(191) NULL,
    ADD COLUMN `contactWidth` INTEGER NOT NULL DEFAULT 120,
    ADD COLUMN `contactX` INTEGER NOT NULL DEFAULT 200,
    ADD COLUMN `contactY` INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN `zelleImagePath` VARCHAR(191) NULL,
    ADD COLUMN `zelleWidth` INTEGER NOT NULL DEFAULT 120,
    ADD COLUMN `zelleX` INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN `zelleY` INTEGER NOT NULL DEFAULT 50;
