-- AlterTable
ALTER TABLE `menu` ADD COLUMN `contentTopOffset` INTEGER NOT NULL DEFAULT 120,
    ADD COLUMN `contentWidth` INTEGER NOT NULL DEFAULT 700,
    ADD COLUMN `overlayOpacity` INTEGER NOT NULL DEFAULT 20;
